# Site settings
title: hackrush
# subtitle: by HTML5 UP
email: some-email@some-mail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
author: hackrush
street_address: Street
city: City
state: Stage
zip_code: 99994447
country: Country
phone: 11452145987

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings
facebook_url: https://www.facebook.com/
github_url: https://github.com/hackrush01

# Build settings
markdown: kramdown

sass:
  style: compressed
